version: '3.8'
services:
  fast_api_test-container:
    build: ./fast_api_test
    container_name: fast_api_test-container
    restart: always
    environment:
      - APP_NAME=MyFastapiApp
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    ports:
      - '5432:5432'
    volumes:
      - postgresql_vol:/var/lib/postgresql/data

volumes:
  postgresql_vol:
